//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT_e_SATIS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Satislar
    {
        public int SATISID { get; set; }
        public Nullable<int> URUN { get; set; }
        public Nullable<int> PERSONEL { get; set; }
        public Nullable<int> MUSTERI { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public Nullable<int> SATICISID { get; set; }
    
        public virtual Tbl_Musteriler Tbl_Musteriler { get; set; }
        public virtual Tbl_Personeller Tbl_Personeller { get; set; }
        public virtual Tbl_Saticilar Tbl_Saticilar { get; set; }
        public virtual Tbl_Urunler Tbl_Urunler { get; set; }
    }
}
