//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT_e_SATIS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Personeller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Personeller()
        {
            this.Tbl_Satislar = new HashSet<Tbl_Satislar>();
        }
    
        public int PERSONELID { get; set; }
        public string PERSONELADSOYAD { get; set; }
        public string PERSONELTELEFON { get; set; }
        public string PERSONELMAIL { get; set; }
        public string PERSONELCINSIYET { get; set; }
        public Nullable<bool> PERSONELDURUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Satislar> Tbl_Satislar { get; set; }
    }
}
