//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT_e_SATIS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MESAJLAR
    {
        public int MESAJID { get; set; }
        public Nullable<int> GONDEREN { get; set; }
        public Nullable<int> ALAN { get; set; }
        public string MESAJICERIK { get; set; }
        public string KONU { get; set; }
        public string ADMINYANIT { get; set; }
    
        public virtual Tbl_Adminler Tbl_Adminler { get; set; }
        public virtual Tbl_Musteriler Tbl_Musteriler { get; set; }
    }
}
