//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT_e_SATIS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Saticilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Saticilar()
        {
            this.Tbl_Satislar = new HashSet<Tbl_Satislar>();
            this.Tbl_Urunler = new HashSet<Tbl_Urunler>();
        }
    
        public int SATICID { get; set; }
        public string SATICIADSOYAD { get; set; }
        public string SATICITELEFON { get; set; }
        public string SATICIMAIL { get; set; }
        public string SATICICINSIYET { get; set; }
        public string SATICIKULLANICIADI { get; set; }
        public string SATICISIFRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Satislar> Tbl_Satislar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Urunler> Tbl_Urunler { get; set; }
    }
}
