//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT_e_SATIS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Duyurular
    {
        public int DUYURUID { get; set; }
        public string DUYURUMETNI { get; set; }
        public Nullable<int> DUYURUYAPAN { get; set; }
    
        public virtual Tbl_Adminler Tbl_Adminler { get; set; }
    }
}
