//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT_e_SATIS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Musteriler()
        {
            this.TBL_MESAJLAR = new HashSet<TBL_MESAJLAR>();
            this.Tbl_Satislar = new HashSet<Tbl_Satislar>();
            this.TBL_SEPETLER = new HashSet<TBL_SEPETLER>();
            this.Tbl_Yorumlar = new HashSet<Tbl_Yorumlar>();
        }
    
        public int MUSTERIID { get; set; }
        public string MUSTERIAD { get; set; }
        public string MUSTERISOYAD { get; set; }
        public Nullable<bool> MUSTERIDURUM { get; set; }
        public string MUSTERIKULLANICIADI { get; set; }
        public string MUSTERISIFRE { get; set; }
        public string MUSTERITELEFON { get; set; }
        public string MUSTERIMAIL { get; set; }
        public string MUSTERIADRES { get; set; }
        public Nullable<decimal> MUSTERIBUTCE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MESAJLAR> TBL_MESAJLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Satislar> Tbl_Satislar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SEPETLER> TBL_SEPETLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Yorumlar> Tbl_Yorumlar { get; set; }
    }
}
